[build-system]
requires = [
    "setuptools >= 64",
    "setuptools_scm >= 7",
]
build-backend = "setuptools.build_meta"

[project]
name = "reaktoro-pse"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "pyomo",
]
[project.optional-dependencies]
testing = [
    "pytest>=8",
]
